[package]
name = "chat-app"
version = "0.1.0"
edition = "2021"
[workspace]
members = [
    "backend",
    "frontend",
    "common"
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
